// Third-party inventory for the simulator, read from package-lock.json and node_modules/.
//
//   node scripts/notices.mjs --check   exit 1 if the inventory section in THIRD_PARTY_NOTICES.md is stale
//   node scripts/notices.mjs --write   regenerate that section in place
//
// vite.config.js imports collect() and emits the same inventory plus every license text into dist/.
// The inventory is every package in the lockfile that is not dev-only (`dev: true`). That is the
// install set, not proof that each package ends up in the bundle: tree-shaking drops some.
import { readFileSync, readdirSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

export const SIM = resolve(dirname(fileURLToPath(import.meta.url)), '..');
export const NOTICES = join(SIM, 'THIRD_PARTY_NOTICES.md');
export const BEGIN = '<!-- inventory:begin (generated by scripts/notices.mjs, do not edit by hand) -->';
export const END = '<!-- inventory:end -->';

const LICENSE_FILE = /^(LICEN[CS]E|COPYING)(\.|$|-)/i;

export function licenseFileName(name, version) {
  return `licenses/${name.replace(/^@/, '').replace(/\//g, '-')}-${version}.txt`;
}

/** Non-dev packages from the lockfile with their license field and license file (if the package has one). */
export function collect() {
  const lock = JSON.parse(readFileSync(join(SIM, 'package-lock.json'), 'utf8'));
  const out = [];
  for (const [key, meta] of Object.entries(lock.packages)) {
    if (!key || meta.dev) continue;
    const name = key.slice(key.lastIndexOf('node_modules/') + 'node_modules/'.length);
    const dir = join(SIM, key);
    let file = null, text = null;
    if (existsSync(dir)) {
      const cands = readdirSync(dir).filter((f) => LICENSE_FILE.test(f)).sort();
      if (cands.length) { file = cands[0]; text = readFileSync(join(dir, file), 'utf8'); }
    } else {
      throw new Error(`notices: ${key} is in package-lock.json but not installed; run npm ci in sim/`);
    }
    out.push({ name, version: meta.version, license: meta.license ?? null, path: key, file, text,
      emit: file ? licenseFileName(name, meta.version) : null });
  }
  out.sort((a, b) => a.name.localeCompare(b.name) || a.version.localeCompare(b.version));
  return out;
}

export function inventoryMarkdown(pkgs) {
  const lines = [
    BEGIN,
    `Packages in \`package-lock.json\` that are not dev-only (${pkgs.length}). \`license\` is the field npm recorded; \`text\` is the license file found in the installed package, shipped next to this file under \`licenses/\`.`,
    '',
    '| package | version | license | text |',
    '|---|---|---|---|',
  ];
  for (const p of pkgs) {
    lines.push(`| \`${p.name}\` | ${p.version} | ${p.license ?? 'none declared'} | ${p.emit ? `[${p.file}](${p.emit})` : 'no license file in the package'} |`);
  }
  lines.push(END);
  return lines.join('\n');
}

/** The notices file with its generated section replaced by a fresh one. */
export function renderNotices(pkgs, source = readFileSync(NOTICES, 'utf8')) {
  const a = source.indexOf(BEGIN), b = source.indexOf(END);
  if (a < 0 || b < 0 || b < a) throw new Error(`notices: markers missing in ${NOTICES}`);
  return source.slice(0, a) + inventoryMarkdown(pkgs) + source.slice(b + END.length);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const mode = process.argv[2];
  const current = readFileSync(NOTICES, 'utf8');
  const fresh = renderNotices(collect(), current);
  if (mode === '--write') {
    writeFileSync(NOTICES, fresh);
    console.log(`notices: wrote ${NOTICES}`);
  } else if (mode === '--check') {
    if (fresh !== current) { console.error('notices: THIRD_PARTY_NOTICES.md inventory is stale; run: node scripts/notices.mjs --write'); process.exit(1); }
    console.log('notices: inventory up to date');
  } else {
    console.error('usage: node scripts/notices.mjs --check | --write'); process.exit(2);
  }
}
