import { chromium, webkit } from 'playwright';
const S = process.env.SHOTS || '/tmp';
const browser = process.env.BROWSER === 'webkit' ? await webkit.launch() : await chromium.launch({ executablePath: process.env.HOME + '/Library/Caches/ms-playwright/chromium-1243/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing' });
const page = await browser.newPage({ viewport: { width: 1280, height: 1000 } });
const errs = [];
page.on('pageerror', (e) => errs.push('pageerror: ' + e.message));
page.on('console', (m) => { if (m.type() === 'error') errs.push(m.text()); });
await page.goto((process.env.BASE || 'http://localhost:4173/') + 'tb.html');
const st = () => page.locator('#status').innerText();
await page.waitForFunction(() => /compile \d+ ms|failed|stopped/.test(document.querySelector('#status').textContent), null, { timeout: 120000 });
console.log('default:', await st());
console.log('out:', (await page.locator('#out').innerText()).split('\n').slice(0, 4).join(' | '));
console.log('canvas h:', await page.locator('#wave').evaluate((c) => c.height));
await page.screenshot({ path: S + '/s-tb.png' });
await page.selectOption('#examples', 'tb: blink');
await page.waitForFunction(() => /compile \d+ ms/.test(document.querySelector('#status').textContent) && document.querySelector('#out').textContent.includes('toggles'), null, { timeout: 120000 });
console.log('blink:', await st());
console.log('blink out tail:', (await page.locator('#out').innerText()).split('\n').slice(-2).join(' | '));
await page.selectOption('#examples', 'tb: traffic light fsm');
await page.waitForFunction(() => /compile \d+ ms/.test(document.querySelector('#status').textContent) && document.querySelector('#out').textContent.includes('la='), null, { timeout: 120000 });
console.log('traffic:', await st());
console.log('traffic out:', (await page.locator('#out').innerText()).split('\n').slice(0, 5).join(' | '));
await page.locator('#wave').hover({ position: { x: 600, y: 40 } });
await page.screenshot({ path: S + '/s-tb-wave.png' });
// compile error path
await page.click('.ftab[data-tab="tb.sv"]');
await page.locator('#editors .editor:not([hidden]) .cm-content').click(); await page.keyboard.press('Meta+a'); await page.keyboard.type('module tb; initial begin $display("x" endmodule');
await page.click('#run');
await page.waitForFunction(() => /failed/.test(document.querySelector('#status').textContent), null, { timeout: 60000 });
console.log('error out:', (await page.locator('#out').innerText()).split('\n').slice(0, 2).join(' | '));
// no $finish → watchdog
await page.locator('#editors .editor:not([hidden]) .cm-content').click(); await page.keyboard.press('Meta+a'); await page.keyboard.type('module tb; logic c=0; always #1 c=~c; endmodule');
const t0 = Date.now();
await page.click('#run');
await page.waitForFunction(() => /stopped/.test(document.querySelector('#status').textContent), null, { timeout: 60000 });
console.log('watchdog after', Math.round((Date.now() - t0) / 1000), 's:', (await page.locator('#out').innerText()).split('\n')[0]);
console.log('errors:', errs.length ? errs : 'none');
await browser.close();
