import { chromium } from 'playwright';
const S = process.argv[2];
const browser = await chromium.launch({ executablePath: process.env.HOME + '/Library/Caches/ms-playwright/chromium-1243/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing' });
const ctx = await browser.newContext({ viewport: { width: 1280, height: 900 } });
const page = await ctx.newPage();
await page.goto('http://localhost:4173/');
await page.waitForFunction(() => /combinational|simulated clock/.test(document.querySelector('#status').textContent), null, { timeout: 180000 });
await page.selectOption('#examples', 'count on the display');
await page.waitForFunction(() => /simulated clock/.test(document.querySelector('#status').textContent), null, { timeout: 60000 });
await page.waitForTimeout(1500);
await page.locator('#board').screenshot({ path: S + '/s-board.png' });
await page.click('#pal button[data-pal=white]');
await page.waitForTimeout(500);
await page.screenshot({ path: S + '/s-white.png' });
await page.setViewportSize({ width: 420, height: 900 });
await page.waitForTimeout(500);
await page.screenshot({ path: S + '/s-mobile.png', fullPage: false });
await page.setViewportSize({ width: 1280, height: 900 });
await page.click('#pal button[data-pal=night]');
await page.goto('http://localhost:4173/docs.html'); await page.waitForTimeout(1500);
await page.screenshot({ path: S + '/s-docs.png' });
await page.goto('http://localhost:4173/cli.html'); await page.waitForTimeout(1500);
await page.screenshot({ path: S + '/s-cli.png' });
await browser.close();
