#!/usr/bin/env python3
"""docs/errors.md + README.md -> site/llms.txt (https://llmstxt.org format).

Run after editing the error catalog or the README; the output is committed. The file is
idempotent: regenerating from the same sources is byte-identical. Links are absolute so the
Vercel mirror (deploy.sh rewrites only root-relative /dewfpga/) serves the same text.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE = "https://nosey-dewdrop.github.io/dewfpga/"
ENTRY = re.compile(r"^## ([a-z0-9][a-z0-9-]*)\s*$")
META = re.compile(r"^(step|source|title|summary|date):\s*(.*)$")


def slug(heading):
    # GitHub/pandoc style id: lowercase, drop punctuation, spaces to hyphens
    s = heading.strip().lower()
    s = re.sub(r"[^\w\s-]", "", s)
    return re.sub(r"\s+", "-", s).strip("-")


def errors(path):
    out, code, meta = [], None, {}
    for line in open(path, encoding="utf-8"):
        line = line.rstrip("\n")
        m = ENTRY.match(line)
        if m:
            if code:
                out.append((code, meta))
            code, meta = m.group(1), {}
            continue
        if code:
            k = META.match(line)
            if k and k.group(1) not in meta:
                meta[k.group(1)] = k.group(2).strip()
    if code:
        out.append((code, meta))
    return out


def readme_sections(path):
    secs = []
    for line in open(path, encoding="utf-8"):
        if line.startswith("## "):
            secs.append(line[3:].strip())
    return secs


def guide_sections(path):
    secs = []
    for line in open(path, encoding="utf-8"):
        if line.startswith("## "):
            secs.append(line[3:].strip())
    return secs


def main():
    err = errors(os.path.join(ROOT, "docs", "errors.md"))
    readme = readme_sections(os.path.join(ROOT, "README.md"))
    guide = guide_sections(os.path.join(ROOT, "docs", "manual-setup.md"))
    missing = [c for c, _ in err if not os.path.isfile(os.path.join(ROOT, "site", "errors", c, "index.html"))]
    if missing:
        sys.exit("llms-build: no site/errors/<code>/index.html for: " + " ".join(missing) + " (run docs/errors-build.sh first)")

    L = []
    L.append("# dewfpga")
    L.append("")
    L.append("> Command-line toolchain that builds SystemVerilog for the Digilent Basys3 (XC7A35T) on an Apple Silicon Mac "
             "without Vivado: `dewfpga sim`, `dewfpga bit`, `dewfpga flash`. Every failure is one line in one format, "
             "`file:line: ERROR [code]: message`, and each code has a page below.")
    L.append("")
    L.append("Generated by docs/llms-build.py from README.md, docs/manual-setup.md and docs/errors.md. Commands exist only "
             "as listed in the README's Commands section; `sim`, `bit`, `check` and `flash` accept `--json` for one "
             "machine-readable result object. Board: Basys3 only. Platform: macOS arm64 only.")
    L.append("")
    L.append("## Docs")
    L.append("")
    L.append(f"- [Install](" + SITE + "install): the one-line installer script (curl | bash)")
    L.append(f"- [CLI](" + SITE + "cli/): what the CLI does, in one page")
    L.append(f"- [Setup guide](" + SITE + "docs/): the manual path, section by section")
    for h in guide:
        L.append(f"- [Guide: {h}](" + SITE + "docs/#" + slug(h) + ")")
    L.append(f"- [Error catalog](" + SITE + "errors/): every code with what you saw, why, the fix and an example")
    L.append(f"- [README](https://github.com/nosey-dewdrop/dewfpga#readme): sections " + ", ".join(readme))
    L.append("")
    L.append("## Errors")
    L.append("")
    for code, meta in err:
        note = meta.get("summary") or meta.get("title") or code
        L.append(f"- [{code}](" + SITE + "errors/" + code + "/): " + note)
    text = "\n".join(L) + "\n"
    out = os.path.join(ROOT, "site", "llms.txt")
    old = open(out, encoding="utf-8").read() if os.path.isfile(out) else None
    if old != text:
        open(out, "w", encoding="utf-8").write(text)
    print(f"site/llms.txt: {len(text.encode())} bytes, {len(err)} error codes, {len(guide)} guide sections")


if __name__ == "__main__":
    main()
